services:
  - type: web
    runtime: node
    name: streamsports99-stremio
    repo: https://github.com/Null9960/streamsports99-stremio
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /manifest.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
